remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Aairish Singh
logo: assets/img/lnly.jpg
description:
  resume: "<a href='https://supersjgk.github.io/'>RESUME</a>"
  linkedin: "<a href='https://www.linkedin.com/in/aairishsingh'>LinkedIn</a>"
theme: jekyll-theme-minimal
